// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Pessoa : BaseEntity
{
    public string Nome { get; set; }

    public string Contato { get; set; }

 }