// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class PessoaEntidade : BaseEntity
{
    public string Nome { get; set; }

    public string Contato { get; set; }

    public int LaboratorioId { get; set; }
    public LaboratorioEntidade Laboratorio { get; set; }

    public virtual UsuarioEntidade Usuario { get; set; }
}